services:
  base:
    image: anansi
    build:
      context: .
      target: development

  dgraph-zero:
    image: dgraph/dgraph:latest
    command: dgraph zero --my=dgraph-zero:8100 --replicas 1
    volumes:
      - dgraph_zero:/dgraph
    ports:
      - "8100:8100"
      - "8101:8101"

  dgraph-alpha:
    image: dgraph/dgraph:latest
    command: dgraph alpha --my=dgraph-alpha:8200 --zero=dgraph-zero:8100 --security whitelist=0.0.0.0/0
    volumes:
      - dgraph_alpha:/dgraph
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - dgraph-zero
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health | grep -q healthy"]
      retries: 3
      interval: 5s
      timeout: 5s

  server-upload:
    image: anansi
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - DGRAPH_URL=http://dgraph-alpha:8000
      - DGRAPH_GRAPHQL_URL=http://dgraph-alpha:8000/graphql
      - DGRAPH_ADMIN_URL=http://dgraph-alpha:8000/admin
    command: npm run dev --workspace=apps/server-upload
    volumes:
      - .:/app
      - server-upload_root_modules:/app/node_modules/
      - server-upload_workspace_modules:/app/apps/server-upload/node_modules/
    ports:
      - "5003:5003"
    depends_on:
      dgraph-alpha:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5003/health"]
      retries: 2
      interval: 5s

  server-query:
    image: anansi
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - DGRAPH_URL=http://dgraph-alpha:8000
      - DGRAPH_GRAPHQL_URL=http://dgraph-alpha:8000/graphql
      - DGRAPH_ADMIN_URL=http://dgraph-alpha:8000/admin
    command: npm run dev --workspace=apps/server-query
    volumes:
      - .:/app
      - server-query_root_modules:/app/node_modules/
      - server-query_workspace_modules:/app/apps/server-query/node_modules/
    ports:
      - "5103:5103"
    depends_on:
      dgraph-alpha:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5103/health"]
      interval: 5s


volumes:
  dgraph_zero:
  dgraph_alpha:
  server-upload_root_modules:
  server-upload_workspace_modules:
  server-query_root_modules:
  server-query_workspace_modules:
